name: extract-deb
version: '0.1'
summary: Extract a .deb package
description: |
  A simple wrapper to dpkg -x to extract .deb packages in a subdirectory
  of your home.
  .
  This is a helpful tool in case you want to access binary .deb content on
  an UbuntuCore system.
  .
  The source can be found at https://github.com/ogra1/extract-deb-snap
  .
  Note that you need to connect the home interface first when using this
  tool on an UbuntuCore system with the command
  snap connect extract-deb:home

grade: stable
confinement: strict

apps:
  extract-deb:
    command: extract-deb
    plugs:
      - home
  download:
    command: download
    plugs:
      - home
      - network
      - network-bind

parts:
  dpkg:
    plugin: nil
    source: https://salsa.debian.org/dpkg-team/dpkg.git
    source-tag: 1.18.4
    override-build: |
      sed -i 's/CONFIGDIR/getenv("$SNAP")/' lib/dpkg/options.c
      fakeroot debian/rules binary
      dpkg -x ../dpkg_*.deb $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/etc/dpkg/* $SNAPCRAFT_PART_INSTALL/
      cp ../../../extract-deb $SNAPCRAFT_PART_INSTALL/
      cp ../../../download $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - autoconf
      - fakeroot
      - dpkg-dev
      - dpkg
      - debhelper
      - pkg-config
      - flex
      - gettext
      - po4a
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libselinux1-dev
      - libncursesw5-dev
      - libio-string-perl
    stage-packages:
      - coreutils
      - grep
      - grep-dctrl
      - gzip
      - wget
