name: extract-deb
version: '0.1'
summary: Extract a .deb package
description: |
  A simple wrapper to dpkg -x to extract .deb packages in a subdirectory
  of your home.
  This is a helpful tool in case you want to access binary .deb content on
  an UbuntuCore system.

grade: devel
confinement: strict

apps:
  extract-deb:
    command: extract-deb
    plugs:
      - home
parts:
  dpkg:
    plugin: nil
    build: |
      echo "deb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted" >>/etc/apt/sources.list
      apt-get update
      apt-get source dpkg
      cd dpkg-*
      sed -i 's/CONFIGDIR/getenv("$SNAP")/' lib/dpkg/options.c
      fakeroot debian/rules binary
    install: |
      cp extract-deb $SNAPCRAFT_PART_INSTALL/
      dpkg -x dpkg_*.deb $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/etc/dpkg/* $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - fakeroot
      - dpkg-dev
      - dpkg
      - debhelper
      - pkg-config
      - flex
      - gettext
      - po4a
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libselinux1-dev
      - libncursesw5-dev
      - libio-string-perl
